import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const poppins = Poppins({
  weight: ['400', '700'],
  subsets:['latin']
})


export const metadata = {
  title: "Gordino Enteprise",
  description: "Generated by Gordino",
  keyword: "wep dev, programing, frontend",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header/>
        <main className="container">
        {children}
        </main>
      </body>
    </html>
  );
}
